name: Generate chromium dist
on:
  push:
    tags:
      - 'chromium-linux-build-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps: &steps
      - run: df -h $HOME
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - run: df -h $HOME
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          pattern: building
          merge-multiple: true
      - run: dekshell rf build.pysh
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: building
          failOnError: false
      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: building
          path: |
            *.tar.gz
            *.zip
            *.done
  build-2:
    needs: build-1
    runs-on: ubuntu-latest
    steps: *steps
  build-3:
    needs: build-2
    runs-on: ubuntu-latest
    steps: *steps
  build-4:
    needs: build-3
    runs-on: ubuntu-latest
    steps: *steps
  build-5:
    needs: build-4
    runs-on: ubuntu-latest
    steps: *steps
  build-6:
    needs: build-5
    runs-on: ubuntu-latest
    steps: *steps
  build-7:
    needs: build-6
    runs-on: ubuntu-latest
    steps: *steps
  build-8:
    needs: build-7
    runs-on: ubuntu-latest
    steps: *steps
  build-9:
    needs: build-8
    runs-on: ubuntu-latest
    steps: *steps
  build-10:
    needs: build-9
    runs-on: ubuntu-latest
    steps: *steps
  build-11:
    needs: build-10
    runs-on: ubuntu-latest
    steps: *steps
  build-12:
    needs: build-11
    runs-on: ubuntu-latest
    steps: *steps
  build-13:
    needs: build-12
    runs-on: ubuntu-latest
    steps: *steps
  build-14:
    needs: build-13
    runs-on: ubuntu-latest
    steps: *steps
  build-15:
    needs: build-14
    runs-on: ubuntu-latest
    steps: *steps
  build-16:
    needs: build-15
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: "chromium-*.zip"
