name: Tests
on:
  push:
    tags:
    - tests-[0-9]+

permissions:
  contents: write

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - run: sudo pip install pdm
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          rm -rf $(sudo python -c "import sysconfig; print(sysconfig.get_path('purelib'))")/urllib3*
          sudo pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && sudo deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          pattern: building
          merge-multiple: true
      - run: sudo apt-get update && sudo apt-get install -y gperf
      - run: sudo which dekshell
      - run: sudo dekshell --help

