name: Generate chromium dist
on:
  push:
    tags:
      - 'tests-[0-9]+-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'

permissions:
    contents: write

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps: &steps
      - run: df -h $HOME
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - run: df -h $HOME
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          pattern: building
      - run: |
          version=$(python -c "print('$GITHUB_REF_NAME'.rsplit('-', 1)[-1])")
          dekchromium build ${version}
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: building
          failOnError: false
      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: building
          path: |
            *.tar.gz
            *.done
  build-2:
    needs: build-1
    runs-on: windows-latest
    steps: *steps
  build-3:
    needs: build-2
    runs-on: windows-latest
    steps: *steps
  build-4:
    needs: build-3
    runs-on: windows-latest
    steps: *steps
