name: Generate chromium dist
on:
  push:
    tags:
      - tests-[0-9]+

permissions:
  contents: write

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir test
          touch test/test1
          tar -c -I "zstd -vv -11 -T0" -f ./test.tar.zst test