name: Generate chromium dist
on:
  push:
    tags:
      - tests-[0-9]+

permissions:
  contents: write

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run --rm chromium-builder:bullseye which gn
