name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+

permissions:
  contents: write

jobs:
  build-1:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v5
      - shell: wsl-bash_Ubuntu-20.04 {0}
        run: |
            docker --help