name: Proxy for audio server
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: df -h $HOME
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: !!bool false
          android: !!bool true
          dotnet: !!bool true
          haskell: !!bool true
          large-packages: !!bool true
          docker-images: !!bool true
          swap-storage: !!bool true
      - run: df -h $HOME
      - run: pip install dekartifacts
      - env:
          GITHUB__DOCKER_REGISTRY: ghcr.io
          GITHUB__DOCKER_USERNAME: ${{ github.actor }}
          GITHUB__DOCKER_PASSWORD: ${{ secrets.GHCR_DOCKER_HUB_PASSWORD }}
        run: |
          dekartifacts docker login
          docker run --rm --entrypoint webui.sh ghcr.io/${{ github.actor }}/mirror:${{ github.actor }}-index-tts-0.1.2 --share
