name: Generate chromium src code
on:
  push:
    tags:
      - 'chromium-windows-src-code-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'
jobs:
  fetch:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - run: dekshell rf upload1.pysh
      - uses: actions/upload-artifact@v4
        with:
          name: tar-xz
          path: |
            *.tar.xz
  pack:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: tar-xz
      - run: dekshell rf upload2.pysh
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: chromium-*.zip.*
