name: Test chromium src code
on:
  push:
    tags:
      - 'chromium-src-full--test-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'
jobs:
  test-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: df -h $HOME
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - run: df -h $HOME
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekplaywright
          token: ${{ secrets.PAT }}
          path: .tmp
      - run: |
          pdm add deksoftware --global
          cd .tmp/dekchromium
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist --extra all
          cd ../..
          dektools file remove .tmp
      - run: dekchromium upload-test
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: chromium-*.zip.*
  test-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekplaywright
          token: ${{ secrets.PAT }}
          path: .tmp
      - run: |
          pdm add deksoftware --global
          cd .tmp/dekchromium
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist --extra all
          cd ../..
          dektools file remove .tmp
      - run: dekchromium upload-test
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: chromium-*.zip.*
  test-macos:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Cleanup Xcode installations
        run: sudo mv /Applications/Xcode_16.app /Applications/tmp_Xcode_16.app ; sudo
          rm -rf /Applications/Xcode* ; sudo mv /Applications/tmp_Xcode_16.app /Applications/Xcode_16.app
      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_16.app
      - name: Cleanup Xcode Simulators
        run: sudo xcrun simctl delete all
      - name: Cleanup Android Related Stuff
        run: sudo rm -rf $ANDROID_HOME
      - name: Disable Spotlight
        run: sudo mdutil -a -i off
      - name: Run xcode-select
        run: sudo xcode-select --switch /Applications/Xcode_16.app
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekplaywright
          token: ${{ secrets.PAT }}
          path: .tmp
      - run: |
          pdm add deksoftware --global
          cd .tmp/dekchromium
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist --extra all
          cd ../..
          dektools file remove .tmp
      - run: dekchromium upload-test
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: chromium-*.zip.*
