name: Generate chromium src code
on:
  push:
    tags:
      - 'chromium-src-full-linux-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: df -h $HOME
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - run: df -h $HOME
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekplaywright
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp/dekchromium
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist --extra all
          cd ../..
          dektools file remove .temp
      - run: dekchromium upload
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: chromium-*.zip.*
