name: Generate chromium src code
on:
  push:
    tags:
      - 'chromium-build-windows-[0-9]+-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          rm -rf ./dist/* && pdm build && deksoftware install whl --path ./dist
          cd ..
          rm -rf .temp
      - run: |
          version=$(python -c "print('$GITHUB_REF_NAME'.rsplit('-', 1)[-1])")
          dekchromium build ${version} ./code
