name: Generate chromium part src code
on:
  push:
    tags:
      - 'chromium-src-part-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'
jobs:
  fetch:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekplaywright
          token: ${{ secrets.PAT }}
          path: .tmp
      - run: |
          pdm add deksoftware --global
          cd .tmp/dekchromium
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist --extra all
          cd ../..
          dektools file remove .tmp
      - run: dekchromium part
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: chromium-*.zip
