name: Generate chromium dist
on:
  push:
    tags:
      - 'chromium-windows-build-full-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build-1:
    runs-on: windows-latest
    steps:
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          pattern: building
          merge-multiple: true
      - run: dekshell rf chromium/build-full.pysh
