name: Proxy for dek8s
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pdm-project/setup-pdm@v3
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dek8s
          token: ${{ secrets.PAT }}
          path: .tmp
      - run: |
          cd .tmp
          pdm build; for filename in dist/*.whl; do break; done; python3 -m pip install $filename; echo $filename > ./self
      - run: |
          sudo apt-get -y install skopeo
      - env:
          DOCKER_DEFAULT_LOGIN_REGISTRY: tencent
          TENCENT__DOCKER_REGISTRY: ccr.ccs.tencentyun.com
          TENCENT__DOCKER_USERNAME: ${{ secrets.TENCENT_DOCKER_HUB_USERNAME }}
          TENCENT__DOCKER_PASSWORD: ${{ secrets.TENCENT_DOCKER_HUB_PASSWORD }}

          DOCKER__DOCKER_REGISTRY: docker.io
          DOCKER__DOCKER_USERNAME: ${{ secrets.DOCKER_DOCKER_HUB_USERNAME }}
          DOCKER__DOCKER_PASSWORD: ${{ secrets.DOCKER_DOCKER_HUB_PASSWORD }}

          GITHUB__DOCKER_REGISTRY: ghcr.io
          GITHUB__DOCKER_USERNAME: ${{ github.actor }}
          GITHUB__DOCKER_PASSWORD: ${{ secrets.GHCR_DOCKER_HUB_PASSWORD }}
        run: |
          dek8s prepare build-controller $(cat ./.tmp/self)
          dek8s prepare sync
