name: Disk size checker
on:
  workflow_dispatch:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: df -h $HOME
  windows:
    runs-on: windows-latest
    steps:
      - run: df -h $HOME
  macos:
    runs-on: macos-latest-large
    steps:
      - run: df -h $HOME
