name: Publish
on:
  push:
    tags:
      - 'chromium-src-[0-9]+-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          cd .temp
          pdm add deksoftware --global
          rm -rf ./dist/* && pdm build && deksoftware install whl --path ./dist
          cd ..
          rm -rf .temp
      - run: |
          version=$(python -c "print('$GITHUB_REF_NAME'.rsplit('-', 1)[-1])")
          dekchromium fetch-code ${version} chromium-${version}.zip
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: chromium-*.zip
