name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  build-1:
    runs-on: macos-latest
    steps:
    - run: 'brew install colima

        brew install docker

        colima start

        '
    - run: df -h --total
    - run: docker run --rm ubuntu df -h --total
