name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - run: pip install dekshell
    - run: |
        dekshell rs "=[(print(x,flush=True), mp.os.system(f'"{x}" --version')) for x in which_list('tar')]"
      shell: cmd
  macos:
    runs-on: macos-15
    steps:
    - run: pip install dekshell
    - run: |
        brew info gnu-tar
        dekshell rs "=[(print(x,flush=True), mp.os.system(f'"{x}" --version')) for x in where_list('tar')]"
