name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  build-1:
    runs-on: macos-15
    steps:
    - run: 'mkdir test

        touch test/test1

        cd test

        tar -c -I "zstd -vv -11 -T0" -f ../test.tar.zst .'
