name: Generate chromium src code
on:
  push:
    tags:
      - 'tests-[0-9]+.[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build-1:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - run: dekshell rf build.pysh
      - uses: actions/upload-artifact@v4
        with:
          name: tar-gz
          path: |
            *.tar.gz
  build-2:
    needs: build-1
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: tar-gz
      - run: dekshell rf build.pysh
  build-3:
    needs: build-2
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: pdm-project/setup-pdm@v3
      - uses: actions/checkout@v3
        with:
          repository: sanzenwin/dekchromium
          token: ${{ secrets.PAT }}
          path: .temp
      - run: |
          pdm add deksoftware --global
          cd .temp
          dektools file remove ./dist && pdm build && deksoftware install whl --path ./dist
          cd ..
          dektools file remove .temp
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: tar-gz
      - run: dekshell rf build.pysh
