name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  build-1:
    runs-on: macos-13
    steps:
    - uses: actions/setup-docker-on-macos@v1-alpha
    - run: df -h --total
    - run: docker run --rm ubuntu df -h --total
