name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  build-1:
    runs-on: windows-latest
    steps:
    - run: |
        where tar
        brew install gnu-tar
        where tar
      shell: cmd
  build-2:
    runs-on: macos-15
    steps:
    - run: |
        which tar
        brew install gnu-tar
        which tar
