name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        fallocate -l 23.68G test.tar
        pip install dekshell
        dekshell rs ">>compress test.tar test.tar.zip"
        dekshell rs ">path.desc test.tar.zip"
