name: Tests
on:
  push:
    tags:
      - 'tests-[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - uses: pdm-project/setup-pdm@v3
      - run: |
          pdm add dektools --global
          which gn
          fallocate -l 1G tests.zip
          dektools file desc tests.zip
          dektools file split tests.zip 314572800
          dektools file meta-split tests.zip
          rm -rf tests.zip          
          dektools file combine tests.zip
          dektools file remove-split tests.zip
          dektools file desc tests.zip
          dektools file hash tests.zip
