name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  build-1:
    runs-on: windows-latest
    steps:
    - run: |
        pip install dekshell
        dekshell rs "=[(print(x), print(mp.os.system(f'{x} --version'))) for x in which_list('tar')]"
      shell: cmd
  build-2:
    runs-on: macos-15
    steps:
    - run: |
        pip install dekshell
        dekshell rs "=[(print(x), print(mp.os.system(f'{x} --version'))) for x in which_list('tar')]"
