name: Generate chromium dist
on:
  push:
    tags:
    - tests-[0-9]+
permissions:
  contents: write
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install dekshell
    - run: |
        dekshell rs '"{>sh.goto {>>cwd}/.gnu-tar.pysh}" --version'
      shell: cmd
  macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v3
    - run: pip install dekshell
    - run: |
        dekshell rs "\"{>sh.goto {>>cwd}/.gnu-tar.pysh}\" --version"
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install dekshell
    - run: |
        dekshell rs "\"{>sh.goto {>>cwd}/.gnu-tar.pysh}\" --version"
